"""add_ai_analysis_fields

Revision ID: ac16b88503fd
Revises: 699fca364c79
Create Date: 2025-05-06 13:03:44.407743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac16b88503fd'
down_revision = '699fca364c79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('ai_analyzed', sa.Boolean(), nullable=True))
    op.add_column('report', sa.Column('ai_category', sa.String(), nullable=True))
    op.add_column('report', sa.Column('ai_severity', sa.String(), nullable=True))
    op.add_column('report', sa.Column('ai_department', sa.String(), nullable=True))
    op.add_column('report', sa.Column('ai_is_valid', sa.Boolean(), nullable=True))
    op.add_column('report', sa.Column('ai_details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'ai_details')
    op.drop_column('report', 'ai_is_valid')
    op.drop_column('report', 'ai_department')
    op.drop_column('report', 'ai_severity')
    op.drop_column('report', 'ai_category')
    op.drop_column('report', 'ai_analyzed')
    # ### end Alembic commands ###