"""add_system_settings_table

Revision ID: fb3fd1f69939
Revises: ac16b88503fd
Create Date: 2025-05-06 18:31:07.433576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb3fd1f69939'
down_revision = 'ac16b88503fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_setting',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('key', sa.String(), nullable=False),
        sa.Column('value', sa.Text(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_setting_id'), 'system_setting', ['id'], unique=False)
    op.create_index(op.f('ix_system_setting_key'), 'system_setting', ['key'], unique=True)
    
    # Insert default system settings
    op.execute(
        "INSERT INTO system_setting (key, value, description) VALUES "
        "('use_vision_api', 'true', 'Enable or disable AI vision analysis'), "
        "('vision_prompt', 'You are a city maintenance expert analyzing problem reports and photos. Analyze the following city maintenance report and photos to determine the category (e.g., \"road damage\", \"graffiti\", \"trash\", \"water leak\", \"broken utility\", \"vegetation\", \"homeless encampment\", \"illegal dumping\", or other appropriate categories), severity (e.g., \"emergency\", \"high\", \"medium\", \"low\"), and responsible department (e.g., \"roads\", \"sanitation\", \"water\", \"parks\", \"police\", \"other\"). Also provide a short assessment of the impact and any recommendations. If this doesn''t appear to be a valid city maintenance report, indicate that in your response.', 'The prompt used for AI vision analysis')"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_setting_key'), table_name='system_setting')
    op.drop_index(op.f('ix_system_setting_id'), table_name='system_setting')
    op.drop_table('system_setting')
    # ### end Alembic commands ###